language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install: "pip install -r dependencies.txt"
# command to run tests
script: run_script.sh
