# Config file for automatic testing at travis-ci.com
language: python

python:
  # Apparently tox can run any python version from this single environment. No need for redundant tests!
  - "2.7"

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  # add environments for every test in tox.ini

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install tox

# command to run tests, e.g. python setup.py test
script: 
  - tox -e $TOX_ENV


